title: Ismael Sandoval
logo: https://media.licdn.com/dms/image/D4E03AQHK4Y1Otlww4w/profile-displayphoto-shrink_800_800/0/1665283824852?e=1678320000&v=beta&t=W222u8OqzvwnNsaX_gFxJN1_jJIgArV8N0nJ11cimF4
description: > # your text below (remove <br> elements if you don't need line breaks)
  Computer science student at UANL, and aspiring data scientist.
  <br><br>
  <a href="https://www.linkedin.com/in/ismael-sandoval/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

