title: Ismael Sandoval
logo: "/images/logo.png?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Computer science student at [UANL](https://www.uanl.mx/en/), and aspiring data scientist.
  <br><br>
  <a href="https://www.linkedin.com/in/ismael-sandoval/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

