theme: jekyll-theme-minimal
title: Ismael Sandoval
description: Computer science student at UANL, and aspiring data scientist.
logo: https://media.licdn.com/dms/image/D4E03AQHK4Y1Otlww4w/profile-displayphoto-shrink_800_800/0/1665283824852?e=1678320000&v=beta&t=W222u8OqzvwnNsaX_gFxJN1_jJIgArV8N0nJ11cimF4
show_downloads: false
